<script setup lang="ts">
import {makeId} from '../storage/id';import {ref} from 'vue';import type {Scenario} from '../types';import {normalize,readLibrary,writeLibrary,encode,decode} from '../storage/library';import type {Entry} from '../storage/library';
const props=defineProps<{scenario:Scenario}>();const emit=defineEmits<{load:[s:Scenario]}>();const entries=ref<Entry[]>([]),name=ref(''),message=ref(''),json=ref('');try{entries.value=readLibrary()}catch{message.value='本地存储不可用或原数据损坏；仍可用 JSON 备份。'}
function persist(){try{writeLibrary(entries.value);message.value='已保存到本地'}catch{message.value='本地存储失败；请导出 JSON 备份'}}
function save(){try{if(entries.value.length>=100)throw Error('最多保存 100 条');entries.value.unshift({id:makeId(),name:name.value.trim().slice(0,120)||'未命名牌局',date:new Date().toISOString(),scenario:normalize(props.scenario)});persist()}catch(e){message.value=(e as Error).message}}
function remove(id:string){entries.value=entries.value.filter(e=>e.id!==id);persist()}
function exportData(){json.value=encode(entries.value);const a=document.createElement('a'),url=URL.createObjectURL(new Blob([json.value],{type:'application/json'}));a.href=url;a.download='poker-lab-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message.value='已生成备份；若预览不支持下载，可复制下方 JSON。'}
function importText(){try{if(json.value.length>2000000)throw Error('文件过大');const imported=decode(json.value);if(entries.value.length+imported.length>100)throw Error('合并后超过 100 条');entries.value.push(...imported);persist()}catch(e){message.value=(e as Error).message}}
async function file(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(f.size>2000000){message.value='文件超过 2MB';return}json.value=await f.text();importText()}
</script><template><details class="panel"><summary>保存与复盘 · 本地资料库</summary><label>牌局名称<input v-model="name" placeholder="例如 翻牌同花听牌"></label><div class="toolbar wrap"><button class="secondary" @click="save">保存当前牌局</button><button class="secondary" @click="exportData">导出全部 JSON</button></div><p class="muted" role="status">{{message}}</p><div class="library-item" v-for="entry in entries" :key="entry.id"><div><strong>{{entry.name}}</strong><small>{{entry.date.slice(0,10)}}</small></div><button class="secondary" @click="emit('load',normalize(entry.scenario))">载入</button><button class="ghost" @click="remove(entry.id)">删除</button></div><p class="muted" v-if="!entries.length">暂无记录。保存的是输入与假设，载入后请重新计算。</p><details><summary>导入文件 / JSON 文本备份</summary><input type="file" accept="application/json,.json" @change="file"><textarea v-model="json" rows="5" placeholder="粘贴备份 JSON，或导出后从这里复制"></textarea><button class="secondary" @click="importText">合并导入 JSON</button></details><p class="muted">无需账号、不上传。清理应用存储可能删除记录，重要牌局请备份。</p></details></template>
