<script setup lang="ts">
import {ref,computed} from 'vue';import type {Scenario} from '../types';import {categories,parseRange,presets} from '../engine/ranges';
const props=defineProps<{scenario:Scenario}>();const emit=defineEmits<{change:[ranges:string[]]}>();const active=ref(0);const selected=computed(()=>Math.min(active.value,props.scenario.opponents-1));
const text=computed(()=>props.scenario.ranges[selected.value]??'random');
const info=computed(()=>{try{const before=parseRange(text.value),after=parseRange(text.value,[...props.scenario.hole,...props.scenario.board].filter((c):c is number=>c!==null));return {before:before.length,after:after.length,error:''}}catch(e){return {before:0,after:0,error:(e as Error).message}}});
function set(value:string){const r=[...props.scenario.ranges];r[selected.value]=value;emit('change',r)}
const selectedCategories=computed(()=>{try{const current=new Set(parseRange(text.value).map(c=>[...c.cards].sort().join()));return new Set(categories.filter(name=>parseRange(name).every(w=>current.has([...w.cards].sort().join()))))}catch{return new Set<string>()}});
function has(name:string){return selectedCategories.value.has(name)}
function toggle(name:string){try{const current=parseRange(text.value);const names=categories.filter(cat=>{const cs=parseRange(cat);return cs.every(w=>current.some(c=>[...c.cards].sort().join()===[...w.cards].sort().join()))});const exists=names.includes(name);set((exists?names.filter(n=>n!==name):[...names,name]).join(', ')||'AA:0')}catch{set(name)}}
</script>
<template><details class="panel"><summary>对手范围 · 每位对手可单独设置</summary><div class="toolbar wrap"><button v-for="n in scenario.opponents" class="secondary" :class="{selected:n-1===selected}" @click="active=n-1">对手 {{n}}</button></div><label>范围文本<textarea :value="text" @input="set(($event.target as HTMLTextAreaElement).value)" rows="3" placeholder="QQ+, AKs, AKo:0.5"></textarea></label><div class="toolbar wrap"><button class="secondary" @click="set(presets.random)">全部随机</button><button class="secondary" @click="set(presets.tight)">强牌示例</button><button class="secondary" @click="set(presets.broad)">较宽示例</button><button class="ghost" @click="set('AA:0')">清空</button></div><p class="error" v-if="info.error">{{info.error}}</p><p class="muted" v-else>组合 {{info.before}} → 排除已知牌后 {{info.after}}。权重写作 :0.5（0–1）；支持对子区间 77-JJ。预设仅是示例。</p><details><summary>13 × 13 范围矩阵</summary><p class="muted">点击矩阵会将当前范围转换为类别开关（权重重置为 1）。对子在对角线，上方同花，下方非同花。</p><div class="range-matrix"><button v-for="cat in categories" :key="cat" :class="{on:has(cat)}" @click="toggle(cat)">{{cat}}</button></div></details></details></template>
