<script setup lang="ts">
import CardTextInput from './components/CardTextInput.vue';import RangeEditor from './components/RangeEditor.vue';import DrawPanel from './components/DrawPanel.vue';import LibraryPanel from './components/LibraryPanel.vue';import DecisionSettings from './components/DecisionSettings.vue';import SensitivityPanel from './components/SensitivityPanel.vue';
import {reactive,ref,computed} from 'vue';import TableView from './components/TableView.vue';import CardPicker from './components/CardPicker.vue';import GameSettings from './components/GameSettings.vue';import ResultPanel from './components/ResultPanel.vue';import {initialScenario} from './types';import type {Scenario} from './types';import {amounts} from './engine/advice';import {useCalculation} from './composables/useCalculation';
const scenario=reactive(initialScenario()),picker=ref<{zone:'hole'|'board';index:number}|null>(null);const {result,busy,progress,error,run,cancel,invalidate}=useCalculation();
const used=computed(()=>[...scenario.hole,...scenario.board].filter((c):c is number=>c!==null));
function update(key:keyof Scenario,value:any){invalidate();Object.assign(scenario,{[key]:value})}
function select(card:number|null){if(!picker.value)return;invalidate();const {zone,index}=picker.value;scenario[zone][index]=card;if(zone==='board'&&card===null)for(let i=index+1;i<5;i++)scenario.board[i]=null;picker.value=null}
function reset(){invalidate();picker.value=null;Object.assign(scenario,initialScenario())}
function example(){reset();Object.assign(scenario,{hole:[12,25],board:[0,14,28,42,8],pot:'100',call:'25',stack:'200',closed:true})}
function calculate(){invalidate();try{amounts(scenario);let empty=false;for(const c of scenario.board){if(c===null)empty=true;else if(empty)throw Error('公共牌需从左到右连续填写，不能跳过中间牌位。')}if(scenario.hole.some(c=>c===null))throw Error('请先选择两张底牌。');run({hole:scenario.hole as number[],board:scenario.board.filter((c):c is number=>c!==null),opponents:scenario.opponents,samples:scenario.samples,ranges:scenario.ranges})}catch(e){error.value=e instanceof Error?e.message:'输入无效'}}
</script>
<template><main><header class="brand"><div><div class="eyebrow">POKER LAB / OFFLINE</div><h1>看清权益，再做决定<span class="beta">范围与复盘版 2.1</span></h1></div><span class="brand-icon">♠</span></header><p class="intro">标准德州扑克 · 加权对手范围 · 离线复盘工具</p><div class="toolbar"><button class="secondary" @click="example">载入示例牌局</button><button class="ghost" @click="reset">重置牌局</button></div><TableView :scenario="scenario" @pick="(zone,index)=>picker={zone,index}"/><CardTextInput @apply="(hole,board)=>{invalidate();scenario.hole=hole;scenario.board=board}"/><GameSettings :scenario="scenario" @update="update"/><RangeEditor :scenario="scenario" @change="r=>update('ranges',r)"/><DecisionSettings :scenario="scenario" @update="update"/><DrawPanel :scenario="scenario"/><section class="run-section"><button class="primary full" v-if="!busy" @click="calculate">计算权益与行动参考 <span>→</span></button><template v-else><button class="secondary full" @click="cancel">取消计算 · {{Math.round(progress*100)}}%</button><progress :value="progress" max="1"></progress></template><p class="error" v-if="error" role="alert">{{error}}</p></section><ResultPanel v-if="result" :result="result" :scenario="scenario"/><SensitivityPanel :scenario="scenario"/><LibraryPanel :scenario="scenario" @load="s=>{invalidate();Object.assign(scenario,s)}"/><details class="panel"><summary>模型说明与开发进度</summary><p class="muted">本版已拆分界面、牌型评估、权益引擎和行动逻辑。小规模转牌／河牌单对手精确枚举，其余场景按设定范围加权模拟。多人联合抽样整组排除牌张冲突。支持取消与错误恢复。</p><p class="muted">已支持独立对手范围、范围假设对比、下一张牌型改善分析、抽水设置和本地复盘。位置仅记录；不解未来下注策略。底池权益是预期分到的底池比例，不只是独赢概率。请勿将本工具当成盈利保证。</p></details><footer>本地计算，不上传牌局 · 不支持边池 / ICM / 短牌</footer></main><CardPicker v-if="picker" :title="picker.zone==='hole'?'底牌 '+(picker.index+1):'公共牌 '+(picker.index+1)" :used="used" :current="scenario[picker.zone][picker.index]" @select="select" @close="picker=null"/></template>
